name: Deploy to xneelo

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Install lftp
      run: sudo apt-get update && sudo apt-get install -y lftp

    - name: Deploy via LFTP
      run: |
        lftp -c "
        set ftp:ssl-allow no;
        set ftp:passive-mode true;
        open -u entzaerzxg,1JdTs6D9422745 196.40.97.146;
        mirror --reverse --delete --verbose . /public_html/ChurchWebsite/ --exclude-glob .git* --exclude-glob .github/
        "
