name: Deploy to xneelo

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Copy files to xneelo via SFTP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: "196.40.97.146"
        username: "entzaerzxg"
        password: "1JdTs6D9422745"
        port: 22
        target: "public_html/ChurchWebsite/"
        source: "."
        rm: false
