name: Deploy to xneelo

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install dependencies & build Astro site
      run: |
        npm ci
        npm run build

    - name: Install lftp
      run: sudo apt-get update && sudo apt-get install -y lftp

    - name: Deploy build output via LFTP
      run: |
        lftp -c "
        set ftp:ssl-allow no;
        set ftp:passive-mode true;
        set net:max-retries 2;
        set net:timeout 10;
        set net:reconnect-interval-base 2;
        open -u entzaerzxg,1JdTs6D9422745 196.40.97.146;
        mirror --reverse --delete --continue --parallel=2 --verbose ./dist /public_html/ChurchWebsite/ --exclude-glob .ht*
        " || true
